### ISSUE TITLE
Potential places to find new headwords

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#14]
While making corrections, the following caught my attention
under headword दशन्

```
16603		<b> -कंठ, -कंधर	<b> दशन्-कंठ, दशन्-कंधर	<+> दशकंठ, दशकंधर	#-m.	$--an epithet of Rāvaṇa, सप्तलोकैकवीरस्य दशकंठकुलद्विषः /Ut./iv.	64
16604		<b> ˚अरि, ˚जित्, ˚रिपु	<b> दशन्-कंठ˚अरि, दशन्-कंठ˚जित्, दशन्-कंठ˚रिपु	<+> दशकंठारि, दशकंठजित्, दशकंठरिपु	#-m.	$--an epithet of Rāma, /R./viii.29.	35
```

Technically, दशकंधरारि, दशकंधरजित्, दशकंधररिपु should also be treated as headwords.

**Comment by gasyoun** [comment]
> Technically, दशकंधरारि, दशकंधरजित्, दशकंधररिपु should also be treated as headwords.

@Andhrabharati agree?

**Comment by Andhrabharati** [comment]
Yes, it has been THE issue throughout.

I seem to have made composite words only with the first primary word, when there are more words as a group for the compounds listed under them.

@drdhaval2785 should probably identify all such 'grouped' primary words above the 'to-be-compounded' secondary words and properly generate the compounds as 'a case', instead of doing it individually when a 'primary' group is noted.

**Comment by gasyoun** [comment]
> should probably identify all such 'grouped' primary words above the 'to-be-compounded' secondary words and properly generate the compounds as 'a case', instead of doing it individually when a 'primary' group is noted.

Why he and not you?

**Comment by drdhaval2785** [comment]
Not much fruitful.
There are only two such cases.
They can be handled manually.

```
16604		<b> ˚अरि, ˚जित्, ˚रिपु	<b> दशन्-कंठ˚अरि, दशन्-कंठ˚जित्, दशन्-कंठ˚रिपु	<+> दशकंठारि, दशकंठजित्, दशकंठरिपु	#-m.	$--an epithet of Rāma, /R./viii.29.	35

43273		<b> ˚जा, ˚तनया	<b> हिम-अद्रि˚जा, हिम-अद्रि˚तनया	<+> हिमाद्रिजा, हिमाद्रितनया	#-f.	$--1. Pārvatī; 2. the Ganges.	29
```
