### ISSUE TITLE
Add scanned pages

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#21]
To allow linking to pages

**Comment by drdhaval2785** [comment]
Added scanned pages at https://github.com/sanskrit-lexicon-scans/lrv.
Waiting till @funderburkjim confirms that the scans work on Cologne server.

**Comment by funderburkjim** [comment]
sh generate_dict.sh lrv  ../../LRVScan/2022/
added to redo_cologne_all.sh in csl-pywork/v02/.

This in preparation for scans.

**Comment by funderburkjim** [comment]
images at Cologne are in scans/LRVScan/pdfpages/
csl-websanlexicon ... dictinfo.php has this.

Also similar change at csl-apidev.

**Comment by funderburkjim** [comment]
## cologne scanned images work

This was a bit tricky, since I chose to use year 2022 (rather than 2020).  I think everything now works.
For proof, try the page containing deva:
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=LRV&page=342-05.
![image](https://user-images.githubusercontent.com/6393033/195689729-95f9ba84-4a35-4c72-8155-ed6f82ad360d.png)

Or try a link in advanced search (or simple-input=deva in csl-apidev).

**Comment by gasyoun** [comment]
> For proof, try the page containing deva

opens

**Comment by drdhaval2785** [comment]
Time to close, @funderburkjim ?

**Comment by funderburkjim** [comment]
Scanned images seem to work fine.  Closing issue.
